language: c
compiler: gcc
script:
  - make cvode
  - make pihm
  - make clean && make flux-pihm
  - make clean && make flux-pihm-bgc
  - make clean && make OMP=on pihm
  - make clean && make OMP=on flux-pihm
  - make clean && make OMP=on flux-pihm-bgc
branches:
  only:
  - master
